Fix stuff in tests

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -8,11 +8,17 @@ if [[ ! -d ~/.vim/plugged/vim-html-template-literals ]]; then
     echo "Can't find vim-html-template-literals"
     exit 1
 fi
+if [[ ! -d ~/.vim/plugged/vim-javascript ]]; then
+    echo "Can't find vim-javascript"
+    exit 1
+fi
 
 vim -Nu <(cat << EOF
 filetype off
 set rtp+=~/.vim/plugged/vader.vim
 set rtp+=~/.vim/plugged/vim-html-template-literals
+set rtp+=~/.vim/plugged/vim-javascript
+set rtp+=~/.vim/plugged/vim-html-template-literals/after
 filetype plugin indent on
 syntax enable
 EOF) +Vader*
